# Generated by Django 5.2.7 on 2026-09-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Optional)')),
                ('service_interested', models.CharField(default='Main Entrance Gate', max_length=150, verbose_name='Item / Service Needed')),
                ('site_location', models.CharField(blank=True, help_text='e.g. Banjara Hills, Hyderabad', max_length=200, verbose_name='Site / Project Location')),
                ('dimensions_or_notes', models.TextField(blank=True, verbose_name='Approximate Dimensions / Requirements')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inquiries/drawings/', verbose_name='Rough Sketch / Blueprint / Site Photo')),
                ('status', models.CharField(choices=[('NEW', '⭐ New Inquiry'), ('CONTACTED', '📞 Contacted / Quoting'), ('SITE_VISIT', '📐 Site Visit Scheduled'), ('COMPLETED', '✅ Deal Closed / Completed'), ('CANCELLED', '❌ Cancelled / Closed')], default='NEW', max_length=30)),
                ('admin_remarks', models.TextField(blank=True, verbose_name='Internal Welder Notes (Quotations, appointments)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Quote & Measurement Request',
                'verbose_name_plural': 'Customer Quote & Measurement Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 14ft Modern Sliding Gate with Laser Cut Panel', max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Heavy cantilever sliding gate with Italian automated motor track', max_length=260)),
                ('description', models.TextField(help_text='Detailed engineering and fabrication notes')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('cover_image_url', models.CharField(blank=True, help_text='Direct static or external fallback image URL', max_length=500)),
                ('steel_grade', models.CharField(default='IS 2062 Grade Mild Steel', help_text='e.g. IS 2062 Structural Mild Steel / Tata Tiscon', max_length=150)),
                ('dimensions', models.CharField(default='Custom Dimensions Available', help_text='e.g. 14ft × 7ft Height (Customizable)', max_length=150)),
                ('thickness_gauge', models.CharField(default='2.0mm Heavy Tube Gauge', help_text='e.g. 2.0mm / 2.5mm MS Square Tube', max_length=150)),
                ('coating_finish', models.CharField(default='Anti-Rust Zinc Primer + 2 Coats PU Enamel', help_text='e.g. Zinc Epoxy Primer + Matte Finish', max_length=150)),
                ('weld_standard', models.CharField(default='AWS D1.1 Certified Welds', help_text='e.g. Full-penetration structural MIG weld', max_length=150)),
                ('estimated_timeline', models.CharField(default='4 - 7 Working Days', help_text='e.g. 3-5 Days Fabrication + 1 Day Installation', max_length=100)),
                ('site_location', models.CharField(default='Hyderabad & Surrounding Regions', help_text='e.g. Jubilee Hills, Hyderabad', max_length=150)),
                ('rating_score', models.DecimalField(decimal_places=1, default=4.9, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=84)),
                ('is_featured', models.BooleanField(default=True, help_text='Feature this card prominently on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Visible to public')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Showcase Item',
                'verbose_name_plural': 'Project Showcase Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Gates & Entrances, Steel Roofs, Car Parking', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('badge_text', models.CharField(default='Heavy Duty Fabrication', help_text='e.g. Heavy Duty, Laser Cut, Pre-Fab', max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='Custom SVG icon code or icon keyword')),
                ('short_description', models.TextField(help_text='Brief summary shown on category headers and cards')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in navbar and page')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this section from the public website')),
            ],
            options={
                'verbose_name': 'Work Category / Section',
                'verbose_name_plural': 'Work Categories / Sections',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sarojini Steel Works', max_length=200)),
                ('tagline', models.CharField(default='Precision Architectural Steel & Heavy Fabrication', max_length=300)),
                ('master_welder', models.CharField(default='Er. Vikram Rao (Certified Welding Specialist)', max_length=150)),
                ('phone', models.CharField(default='+91 98450 12345', max_length=50)),
                ('whatsapp_number', models.CharField(default='919845012345', help_text='Number with country code, no + or spaces', max_length=30)),
                ('email', models.EmailField(default='contact@sarojinisteel.com', max_length=254)),
                ('workshop_address', models.CharField(default='Plot 42, Heavy Industrial Fabrications Yard, Phase 2', max_length=300)),
                ('city', models.CharField(default='Hyderabad, Telangana', max_length=100)),
                ('working_hours', models.CharField(default='Mon - Sat: 8:00 AM - 7:30 PM (Sunday Site Visits on Request)', max_length=150)),
                ('years_experience', models.PositiveIntegerField(default=15)),
                ('projects_completed', models.PositiveIntegerField(default=650)),
                ('warranty_years', models.PositiveIntegerField(default=10)),
                ('certification_badge', models.CharField(default='AWS D1.1 Structural Welding & IS 2062 Grade Steel', max_length=200)),
                ('google_maps_url', models.URLField(blank=True, default='https://maps.google.com', max_length=500)),
            ],
            options={
                'verbose_name': 'Workshop Profile & Contact Settings',
                'verbose_name_plural': 'Workshop Profile & Contact Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, help_text='e.g. Weld seam close-up, installation on site', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='showcase.projectshowcase')),
            ],
            options={
                'verbose_name': 'Project Gallery Photo',
                'verbose_name_plural': 'Project Gallery Photos',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projectshowcase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='showcase.workcategory'),
        ),
    ]
